/* automatically generated by rust-bindgen 0.65.1 */

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct xaiocp_s {
    _unused: [u8; 0],
}
extern "C" {
    pub fn xaiocp_new(result: *mut *mut xaiocp_s) -> i32;
}
