extern crate autocfg;
extern crate cbindgen;

use std::env;

#[allow(clippy::field_reassign_with_default)]
fn main() {
    let ac = autocfg::new();
    ac.emit_expression_cfg("libc::MSG_DONTWAIT", "has_libc_MSG_DONTWAIT");
    let crate_dir = env::var("CARGO_MANIFEST_DIR").unwrap();
    let mut config: cbindgen::Config = Default::default();
    config.language = cbindgen::Language::C;
    config.cpp_compat = true;
    config.include_guard = Some("XAIO_H".into());
    config.autogen_warning = Some(
        "/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */".into(),
    );
    config.no_includes = true;
    config.sys_includes = vec!["stdint.h".into(), "stdbool.h".into(), "stddef.h".into()];
    config.after_includes = Some(
        r"
#ifndef _Nonnull
#   define _Nonnull
#endif
#ifndef AtomicUsize
#   define AtomicUsize _Atomic uintptr_t
#endif
#if !defined(__GNUC__) && !defined(__clang__)
#   define __attribute__()
#endif
    "
        .into(),
    );
    config.documentation = true;
    config.documentation_style = cbindgen::DocumentationStyle::Doxy;
    config.style = cbindgen::Style::Tag;
    config.pointer.non_null_attribute = Some("_Nonnull".into());
    config.function.must_use = Some("__attribute__((warn_unused_result))".into());
    config.function.deprecated = Some("__attribute__((deprecated))".into());
    config.function.no_return = Some("__attribute__((noreturn))".into());
    cbindgen::Builder::new()
        .with_crate(crate_dir)
        .with_config(config)
        .generate()
        .expect("Unable to generate bindings")
        .write_to_file("include/xaio.h");
    autocfg::rerun_path("build.rs");
}
