[workspace]

members = [ "libdir",
    "xaio-core2",
    "xaio-core",
    "xaio-future", "coro",
]
resolver = "2"

[workspace.dependencies]
libc = "0.2"
bitflags = "2.6.0"
num = "0.4.3"
rustc-hash = "2.1.0"
socket2 = { version = "0.5.8", features = ["all"]}
cfg-if = "1.0.0"
log = "0.4.22"
