[package]
name = "xaio-core2"
version = "0.1.0"
edition = "2021"

[dependencies]
libc = { workspace = true }
log = { workspace = true }
cfg-if = { workspace = true }
enum_dispatch = "0.3"

[dev-dependencies]
env_logger = "0.11.6"