[package]
name = "coro"
version = "0.1.0"
edition = "2021"

[dependencies]
libc = { workspace = true }
log = { workspace = true }
cfg-if = { workspace = true }
anyhow = "1.0"

[dev-dependencies]
env_logger = "0.11.6"